//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electro_E_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Orders()
        {
            this.tb_Orders_Summary = new HashSet<tb_Orders_Summary>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<decimal> shipping_cost { get; set; }
        public string order_status { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public string remarks { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> updated_by { get; set; }
    
        public virtual tb_Admin tb_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Orders_Summary> tb_Orders_Summary { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
