//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electro_E_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Products()
        {
            this.tb_Orders_Summary = new HashSet<tb_Orders_Summary>();
            this.tb_Review = new HashSet<tb_Review>();
            this.tb_Wishlist = new HashSet<tb_Wishlist>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string product_name { get; set; }
        public string product_img { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> stock { get; set; }
        public string model { get; set; }
        public string manufacturer { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
    
        public virtual tb_Admin tb_Admin { get; set; }
        public virtual tb_Categories tb_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Orders_Summary> tb_Orders_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Review> tb_Review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Wishlist> tb_Wishlist { get; set; }
    }
}
